language: ruby

rvm:
  - 2.3.0

bundler_args: --without development --deployment

cache: bundler

before_script:
  - bundle exec rake db:create  
  - bundle exec rake db:migrate  

script:
  - bundle exec rake test
  - bundle exec brakeman
  - bundle exec bundle-audit check --update
